### ISSUE TITLE
interfaceの切り分け

### ISSUE THREAD

**Issue by yamawo** [ishihaya/demo-ahiboh#12]
https://github.com/ishihaya/demo-ahiboh/blob/d1e7eaf02faf99129c209e740593fb0a36612e8f/react/src/components/News/NewsData.tsx#L2

`interface` という名前のフォルダを作られて、型定義ファイルを切り分けられているのすごく良いと思います！

今でこそ実感できないかもしれませんが、interfaceやロジックは何回も繰り返し使う（使えるように書く）ことになると思うので、この部分も切り分けておいて損はないと思います！

**Comment by ishihaya** [comment]
ありがとうございます！
本番開発時に意識して取り組みたいと思います！
